language: python
sudo: false
python:
  - "3.5"
install:
  # download Scilab and add it to the path
  - |
    if [[ $ENV == python=3.3* ]]; then
      wget http://www.scilab.org/download/5.4.1/scilab-5.4.1.bin.linux-x86_64.tar.gz  -O scilab.tar.gz;
      tar xfz scilab.tar.gz;
      export PATH="$PWD/scilab-5.4.1/bin:$PATH";
    else
      wget http://www.scilab.org/download/5.5.1/scilab-5.5.1.bin.linux-x86_64.tar.gz -O scilab.tar.gz;
      tar xfz scilab.tar.gz;
      export PATH="$PWD/scilab-5.5.1/bin:$PATH";
    fi
  - scilab -version; true
  - pip install ipykernel jupyter_client traitlets jupyter_kernel_test flit
  - flit install
  - python -m scilab_kernel.install
script:
  - python test_scilab_kernel.py
